### ISSUE TITLE
extension prevents deletion of published children pages and throws application error messages

### ISSUE THREAD

**Issue by dko** [jgarber/radiant-chronicle-extension#29]
_double posted in an attempt to file as bug_

Hi Jason, 
Thanks for creating chronicle. I really like the whole concept of this extension. There is however at the moment a bug which prevents me from using it:
After the creation of a child page, publish then you won't be able to delete said page.
Workaround is to change the page status to "draft" save page then you can delete.
But upon going back to "History" tab the extension throws "application error" type 500

I'm on Radiant 0.7.1

Always Victory!

**Comment by koppen** [comment]
Without fully understanding the issue, it seems I have at least fixed the part with the "History" tab throwing an application error. The changes are at http://github.com/koppen/radiant-chronicle-extension/commit/5aaf8a0fd852a1adfe612a35f1b680d64d70efca

**Comment by jgarber** [comment]
Well, I fixed the inability to delete that you described.  I was unable to duplicate it through the interface, but fortunately I had an old database lying around that exhibited that behavior.  The page version in the main table was ahead of the versioned instance (I can't figure out how), and that would cause the StaleObjectError that wouldn't let you delete the page.  Not sure why you were getting a 500 error on the History tab, then.  Deleting the page should, at this point at least, delete all the version history as well.  Upgrade to 0.8 and the latest chronicle and let me know if you experience this again.  Thanks for reporting the bug.

**Comment by asf** [comment]
Hi Jason,

this is a really great extension.  Today I still got the application error on the History tab after deleting a page.  It did not get deleted from the versions table.

Running radiant version 0.8.1 and chronicle 2.0

Thanks,
Andreas

**Comment by nicholasjhenry** [comment]
Andreas, I believe the presence of the reorder extension causes this problem. Try setting the explicit load order of your extensions in environment.rb with Chronicle first. e.g.   config.extensions = [ :reorder, :chronicle ]
