### ISSUE TITLE
Unpublished Childs not available in tags like <r:children:each> in dev mode

### ISSUE THREAD

**Issue by andreash** [jgarber/radiant-chronicle-extension#32]
I am creating a menu using the <r:children:each> tag (for example). I am in dev mode but the tag still would only find published childs, not the unpublished ones. It would be great to see the unpublished as well being found by the tag, to have a "complete" impression on how the page would look and feel (e.g. links in the menus).
Thanks,
Andreas

**Comment by jgarber** [comment]
From my testing, it looks like the tag _does_ find unpublished children by default in dev mode, but doesn't retrieve the draft version of a published page.  So, if you create a new page as a draft, it would show up, but a published page that you edited as a draft would show the information from the live version, not the dev version.

**Comment by jgarber** [comment]
Okay, I've pushed a fix for this.

**Comment by jgarber** [comment]
Oops.  Just thought about it that parent.current should only be done if dev.

**Comment by jgarber** [comment]
It's been a long time, but I think I fixed it today.
