### ISSUE TITLE
MissingSourceFile: application.rb - Update for 0.8

### ISSUE THREAD

**Issue by valmiki** [jgarber/radiant-chronicle-extension#34]
when installing via .script

Could not load extension from file: chronicle_extension.
# <MissingSourceFile: no such file to load -- application.rb>

rake aborted!
no such file to load -- application.rb

on radiant 0.8.0

**Comment by jgarber** [comment]
It hasn't been updated for 0.8 yet.  Will do.

**Comment by seancribbs** [comment]
This issue has already been resolved.
