### ISSUE TITLE
Layout information not consistent

### ISSUE THREAD

**Issue by andreash** [jgarber/radiant-chronicle-extension#35]
I use the Reorder-Extension together with your Extension. My draft version of the page has a different layout then the published page. If I now save the draft version as published _with_ the different layout  the layout changes in the select box and is saved, but appearently not fully correctly. Calling up the published page (www.xxx.yyy) still leads to the old layout. ONLY if I reposition the page by using the Reorder extension, then the select box shows that the page still has the old layout. If I then change it again to the new layout, then the change is stored correctly and the page shows with the correct layout.

**Comment by jgarber** [comment]
Fix the problem of layout not being saved when it was changed in a previous draft version and you are now publishing it.  Closed by 0d3cf2014bd24b8f3d4be4cc0880f7a4883a3403.
