### ISSUE TITLE
SystemStackError (stack level too deep)

### ISSUE THREAD

**Issue by seantanly** [jgarber/radiant-chronicle-extension#39]
Encountered the above error when using fresh install of Radiant with default example and just Chronicle. 

Seems that the "alias_method_chain :find, :draft_versioning" got called multiple times. 

Stack Trace as follows:

/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/lib/chronicle/association_collection_extensions.rb:13:in `puts'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/lib/chronicle/association_collection_extensions.rb:13:in`find_without_draft_versioning'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/lib/chronicle/association_collection_extensions.rb:15:in `find_without_draft_versioning'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/lib/chronicle/association_collection_extensions.rb:15:in`find'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/lib/chronicle/simple_model_extensions.rb:43:in `versions_with_limit'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/app/helpers/admin/timeline_helper.rb:68:in`versions_for_timeline'
/dev/rails_apps/gameportal_radiant/vendor/extensions/chronicle/app/views/admin/_timeline.html.haml:4:in `_run_haml_vendor47extensions47chronicle47app47views47admin47_timeline46html46haml_locals_defaults_object_timeline'
/dev/ruby/lib/ruby/gems/1.8/gems/radiant-0.8.0/vendor/rails/actionpack/lib/action_view/renderable.rb:34:in`send'
/dev/ruby/lib/ruby/gems/radiant-0.8.0/vendor/rails/actionpack/lib/action_view/renderable.rb:34:in `render'

**Comment by jgarber** [comment]
Fix a problem with reloading in dev environment. Closed by 8352ec68390f9ea9593574d3ef285966760a9ec9.

**Comment by seantanly** [comment]
Thanks, the problem went away. =)
