### ISSUE TITLE
(layout/snippet).status is undefined

### ISSUE THREAD

**Issue by ShadowBelmolve** [jgarber/radiant-chronicle-extension#40]
When acessing Layouts/Snippets page I got this error:

You have a nil object when you didn't expect it!
The error occurred while evaluating nil.name

Extracted source (around line #26): 
26:             %td.status{:class => "#{snippet.status.name.downcase}-status"}
Extracted source (around line #31): 
31:             %td.status{:class => "#{layout.status.name.downcase}-status"}

Radiant 0.8.0(gem) and chronicle installed today

**Comment by jgarber** [comment]
I'm not able to duplicate.  I have a hunch it was fixed in f3a28. Can you confirm?

**Comment by jgarber** [comment]
Going to assume it was fixed since I can't duplicate the problem.
