### ISSUE TITLE
Make "View page after saving" work when using script/server

### ISSUE THREAD

**Issue by kintner** [jgarber/radiant-chronicle-extension#45]
In chronicle/app/helpers/admin/preview_helper.rb change line 13 to 

```
host =~ /^localhost/ ? host : Radiant::Config['dev.host'] || ("dev." + host)
```

**Comment by jgarber** [comment]
Make "View page after saving" work when using script/server. Closed by 1b7baa48701e45d12b663e53c9f7dd3fbbcdbc16.
