### ISSUE TITLE
cannot get to work with multi_site

### ISSUE THREAD

**Issue by catmando** [jgarber/radiant-chronicle-extension#54]
This might be some weird problem with my setup, but I get errors all over the place like the following unless I disable multi_site:

wrong arguments (1 for 0)  3/mnt/vendor/extensions/chronicle/lib/chronicle/page_extensions.rb:76:in `url'

seems to occur anyplace that  page.url(...) is called.

**Comment by jgarber** [comment]
Yeah, I'm pretty sure it's not compatible with mult_site. I had intended to rewrite chronicle to be compatible, but haven't gotten around to it.

**Comment by catmando** [comment]
This appears to be a problem in multi_site:

page.url is aliased, but does not take the optional parameter.   So Chronicle's calls to page.url where it passes the live value fail.  I added the parameter to multi_site, and things are better.  However I have not quite figured out what multi_site should be doing with that value.

I will put a problem in multi-site.
